baseurl = "https://bordeline.studio/"
title = "Bordeline Games"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
author = "Bordeline games"
description = "Gilad Maoz and Yoan Funaro game studio"
keywords = "bordeline, games, studio"
info = ""
avatarurl = "images/ons.png"
footercontent = "Bordeline games studio 2020"

dateformat = "January 2, 2006"

hideFooter = false
hideCredits = true
hideCopyright = true
since = 2020
rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorscheme = "auto"

# Hide the toggle button, along with the associated vertical divider
hidecolorschemetoggle = false

# Series see also post count
maxSeeAlsoItems = 5

# Enable Twemoji
enableTwemoji = true

# Custom CSS
customCSS = []

# Custom SCSS
customSCSS = []

# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
#siteID = "ABCDE"
# Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
#[params.plausibleAnalytics]
#domain = "example.com"
# Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
#[params.goatCounter]
#code = "code"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/Bordeline"

[languages]
[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Games"
weight = 3
url = "games/"

[[languages.en.menu.main]]
name = "Contact us"
weight = 5
url = "contact/"